### ISSUE TITLE
きれいなグラフとか表示してみる(スピログラフ)

### ISSUE THREAD

**Issue by Nanohatan** [shiCanoko/practice_processing#1]
スピログラフ wiki:https://ja.wikipedia.org/wiki/スピログラフ

**Comment by Nanohatan** [comment]
参考になりそう
理論：http://www.mathematische-basteleien.de/spirographs.htm#Drawing%20Exercises
code：https://n.mtng.org/prog/Spirograph/Spirograph.pde

**Comment by shiCanoko** [comment]
いいね
